apiVersion: v1
kind: Pod
metadata:
  name: cluster-ip
  labels:
    environment: dev
    app: web
  # namespace: roboshop
spec:
  containers:
    - name: cluster-ip
      image: nginx:latest
      ports:
      - containerPort: 80
        name: nginx-web-svc

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-service
# spec:
#   selector:
