apiVersion: v1
kind: Pod
metadata:
  name: nodeport-ip
  labels:
    environment: dev
    app: web
  # namespace: roboshop
spec:
  containers:
    - name: nodeport-ip
      image: nginx:latest
      ports:
      - containerPort: 80
        name: nginx-web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  selector:
    type: NodePort
    environment: dev
    app: web
  ports:
  - name: nodeport-service
    protocol: TCP
    port: 80 # this port belongs to service
    targetPort: nginx-web-svc # this port belongs to container