apiVersion: v1
kind: Pod
metadata:
  name: configmap
  labels:
    environment: dev
    app: nginx
spec:
  containers:
  - name: configmap
    image: nginx
    envFrom:
    - configMapRef:
        name: course-config
