apiVersion: v1
kind: Pod
metadata:
  name: configmap
  labels:
    environment: dev
    app: nginx
spec:
  containers:
  - name: configmap
    image: nginx
    env:
    - name: peru
      valueFrom:
        configMapKeyRef:
          name: course-config
          key: name
    - name: Dad
      valueFrom:
        configMapKeyRef:
          name: course-config
          key: father-name
    - name: desam
      valueFrom:
        configMapKeyRef:
          name: course-config
          key: country


          