apiVersion: v1
kind: Pod
metadata:
  name: multi-containers
spec: 
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
    - name: demo-linux
      image: alma-linux:8