apiVersion: v1
kind: Pod
metadata:
  name: nginx-sample
  Namespace: roboshop
spec:
  containers:
    - name: nginx-demo
      image: nginx
      ports:
      - containerPort: 80
    - name: docker-demo
      image: docker
      ports:
      - containerPort: 8080