apiVersion: v1
kind: Secret
metadata:
  name: secret-auth
data:
  username: bWFoZXNoCg==
  password: aGFyaQo=
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    environment: dev
    app: nginx
spec:
  containers:
  - name: secret-pod
    image: nginx
    envFrom:
    - secretRef:
        name: secret-auth
